spring.application.name=StripeIntegrationService
server.port=8081
stripe.secret.key=sk_test_tR3PYbcVNZZ796tH88S4VQ2u
stripe.url=https://api.stripe.com/v1/checkout/sessions
stripe.url.get=https://api.stripe.com/v1/checkout/sessions/{id}
stripe.url.expire=https://api.stripe.com/v1/checkout/sessions/{id}/expire

